/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Secondary */

#ifndef _Included_Secondary
#define _Included_Secondary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Secondary
 * Method:    sort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_Secondary_sort
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Secondary
 * Method:    getMemAccess
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Secondary_getMemAccess
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
